[2025-10-23T17:04:45.476+0000] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: ckan_data_etl.load manual__2024-09-01T00:00:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2025-10-23T17:04:45.475892+00:00 and task will be retried at 2025-10-23T17:09:41.642716+00:00.
[2025-10-23T17:04:45.503+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
