[2025-10-23T17:35:26.253+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ckan_data_etl.transform manual__2025-10-23T17:14:44.489126+00:00 [queued]>
[2025-10-23T17:35:26.261+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ckan_data_etl.transform manual__2025-10-23T17:14:44.489126+00:00 [queued]>
[2025-10-23T17:35:26.262+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-10-23T17:35:26.273+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2025-10-23 17:14:44.489126+00:00
[2025-10-23T17:35:26.280+0000] {standard_task_runner.py:57} INFO - Started process 63 to run task
[2025-10-23T17:35:26.283+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ckan_data_etl', 'transform', 'manual__2025-10-23T17:14:44.489126+00:00', '--job-id', '841', '--raw', '--subdir', 'DAGS_FOLDER/crypto_etl_dag.py', '--cfg-path', '/tmp/tmpwv1p3jyr']
[2025-10-23T17:35:26.285+0000] {standard_task_runner.py:85} INFO - Job 841: Subtask transform
[2025-10-23T17:35:26.349+0000] {task_command.py:416} INFO - Running <TaskInstance: ckan_data_etl.transform manual__2025-10-23T17:14:44.489126+00:00 [running]> on host 056dd0d0c4ba
[2025-10-23T17:35:26.430+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ckan_data_etl' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-10-23T17:14:44.489126+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-23T17:14:44.489126+00:00'
[2025-10-23T17:35:26.446+0000] {logging_mixin.py:154} INFO - Transform - Retrieved 63 records from extract task
[2025-10-23T17:35:26.450+0000] {logging_mixin.py:154} INFO - DataFrame shape: (63, 16)
[2025-10-23T17:35:26.465+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crypto_etl_dag.py", line 38, in transform_data
    df.to_excel(excel_path, index=False, engine='openpyxl')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2252, in to_excel
    formatter.write(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/excel.py", line 934, in write
    writer = ExcelWriter(  # type: ignore[abstract]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 56, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
[2025-10-23T17:35:26.481+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ckan_data_etl, task_id=transform, execution_date=20251023T171444, start_date=20251023T173526, end_date=20251023T173526
[2025-10-23T17:35:26.491+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 841 for task transform (No module named 'openpyxl'; 63)
[2025-10-23T17:35:26.536+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-23T17:35:26.561+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
