[2025-10-23T17:37:28.678+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ckan_data_etl.transform scheduled__2024-11-19T00:00:00+00:00 [queued]>
[2025-10-23T17:37:28.695+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ckan_data_etl.transform scheduled__2024-11-19T00:00:00+00:00 [queued]>
[2025-10-23T17:37:28.696+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-10-23T17:37:28.716+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2024-11-19 00:00:00+00:00
[2025-10-23T17:37:28.726+0000] {standard_task_runner.py:57} INFO - Started process 169 to run task
[2025-10-23T17:37:28.734+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ckan_data_etl', 'transform', 'scheduled__2024-11-19T00:00:00+00:00', '--job-id', '863', '--raw', '--subdir', 'DAGS_FOLDER/crypto_etl_dag.py', '--cfg-path', '/tmp/tmpppw69x3q']
[2025-10-23T17:37:28.737+0000] {standard_task_runner.py:85} INFO - Job 863: Subtask transform
[2025-10-23T17:37:28.822+0000] {task_command.py:416} INFO - Running <TaskInstance: ckan_data_etl.transform scheduled__2024-11-19T00:00:00+00:00 [running]> on host 056dd0d0c4ba
[2025-10-23T17:37:28.930+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ckan_data_etl' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-11-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-19T00:00:00+00:00'
[2025-10-23T17:37:28.957+0000] {logging_mixin.py:154} INFO - Transform - Retrieved 63 records from extract task
[2025-10-23T17:37:28.967+0000] {logging_mixin.py:154} INFO - DataFrame shape: (63, 16)
[2025-10-23T17:37:28.989+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crypto_etl_dag.py", line 38, in transform_data
    df.to_excel(excel_path, index=False, engine='openpyxl')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2252, in to_excel
    formatter.write(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/excel.py", line 934, in write
    writer = ExcelWriter(  # type: ignore[abstract]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 56, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
[2025-10-23T17:37:29.005+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ckan_data_etl, task_id=transform, execution_date=20241119T000000, start_date=20251023T173728, end_date=20251023T173729
[2025-10-23T17:37:29.020+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 863 for task transform (No module named 'openpyxl'; 169)
[2025-10-23T17:37:29.066+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-23T17:37:29.104+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
