[2025-10-23T17:37:21.802+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ckan_data_etl.transform manual__2025-10-23T17:36:41.570305+00:00 [queued]>
[2025-10-23T17:37:21.819+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ckan_data_etl.transform manual__2025-10-23T17:36:41.570305+00:00 [queued]>
[2025-10-23T17:37:21.820+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-10-23T17:37:21.847+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2025-10-23 17:36:41.570305+00:00
[2025-10-23T17:37:21.859+0000] {standard_task_runner.py:57} INFO - Started process 119 to run task
[2025-10-23T17:37:21.865+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ckan_data_etl', 'transform', 'manual__2025-10-23T17:36:41.570305+00:00', '--job-id', '849', '--raw', '--subdir', 'DAGS_FOLDER/crypto_etl_dag.py', '--cfg-path', '/tmp/tmpfo1ibh0l']
[2025-10-23T17:37:21.868+0000] {standard_task_runner.py:85} INFO - Job 849: Subtask transform
[2025-10-23T17:37:21.961+0000] {task_command.py:416} INFO - Running <TaskInstance: ckan_data_etl.transform manual__2025-10-23T17:36:41.570305+00:00 [running]> on host 056dd0d0c4ba
[2025-10-23T17:37:22.049+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ckan_data_etl' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-10-23T17:36:41.570305+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-23T17:36:41.570305+00:00'
[2025-10-23T17:37:22.075+0000] {logging_mixin.py:154} INFO - Transform - Retrieved 63 records from extract task
[2025-10-23T17:37:22.083+0000] {logging_mixin.py:154} INFO - DataFrame shape: (63, 16)
[2025-10-23T17:37:22.131+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crypto_etl_dag.py", line 38, in transform_data
    df.to_excel(excel_path, index=False, engine='openpyxl')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2252, in to_excel
    formatter.write(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/excel.py", line 934, in write
    writer = ExcelWriter(  # type: ignore[abstract]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 56, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
[2025-10-23T17:37:22.153+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ckan_data_etl, task_id=transform, execution_date=20251023T173641, start_date=20251023T173721, end_date=20251023T173722
[2025-10-23T17:37:22.168+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 849 for task transform (No module named 'openpyxl'; 119)
[2025-10-23T17:37:22.197+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-23T17:37:22.230+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
